# Generated by Django 3.2.7 on 2024-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=150)),
                ('file', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=120)),
            ],
        ),
    ]
