# Generated by Django 3.2.7 on 2024-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('booking', models.CharField(max_length=150)),
            ],
        ),
    ]
