# Generated by Django 3.2.7 on 2024-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0003_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='phone_number',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
