# Generated by Django 3.2.7 on 2024-03-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0004_officer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='booking',
        ),
    ]
