# Generated by Django 3.2.7 on 2024-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0005_remove_officer_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=150)),
                ('officer_id', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
            ],
        ),
    ]
