# Generated by Django 3.2.7 on 2024-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
