# Generated by Django 3.1.2 on 2025-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy', '0009_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookings',
        ),
        migrations.DeleteModel(
            name='officer',
        ),
        migrations.DeleteModel(
            name='results',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
